name: isola
description: This is isola OS image.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  - from-file: common-packages.yml
  - from-file: common-flatpaks.yml
  - from-file: common-fonts.yml
  - from-file: common-akmods.yml
  - from-file: common-files.yml
  - from-file: common-systemd.yml
  - from-file: common-signing.yml
