# image will be published to ghcr.io/<user>/<name>
name: isola
description: This is isola OS image.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-%OS_VERSION%.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-%OS_VERSION%.noarch.rpm
    install:
      - code
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "flathub"
      install:
        - com.github.tchx84.Flatseal
        - io.github.flattool.Warehouse
        - io.missioncenter.MissionCenter
        - org.mozilla.firefox
        - com.valvesoftware.Steam
        - com.usebottles.bottles
        - com.github.Matoking.protontricks
        - org.telegram.desktop
        - com.spotify.Client
      remove:
        - org.gnome.eog

  - type: brew
    nofile-limits: true
    brew-analytics: false

  - type: fonts
    fonts:
      nerd-fonts:
        - NerdFontsSymbolsOnly
        - Hack

  - type: akmods
    base: asus
    install:
      - openrgb

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
